<?php

class Firebase {
    public static string $api_key = "AIzaSyDEYutj0oIxaws-91a3oEfcTLUziXDghQc";
    public static function get_user($token) {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
    
        curl_setopt($ch, CURLOPT_URL, 'https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=' . Firebase::$api_key);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(array("idToken" => $token)));
    
        $headers = array();
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
        $result = json_decode(curl_exec($ch));
        if (curl_errno($ch)) {
            throw new Exception("Check_token exception");
        }
        curl_close($ch);

        if ($result->users) {
            return $result->users[0];
        } else {
            throw new BadReqException("Invalid token");
        }
    }
}



?>